/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useMemo, useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { Group, Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three/examples/jsm/Addons.js";

export default function WallCorner(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<Group>(null);
  const { nodes, materials } = useGLTF("/wallCorner.gltf.glb");
  const node0 = useMemo(() => nodes.Cube4531.clone(), [nodes]);
  const node1 = useMemo(() => nodes["Cube4531_1"].clone(), [nodes]);
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive
        object={node0}
        material={materials.Stone}
        receiveShadow
        position={[0.0001, 0.0001, 0.0001]}
      />
      <primitive object={node1} receiveShadow material={materials.StoneDark} />
    </group>
  );
}

useGLTF.preload("/wallCorner.gltf.glb");
