/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { Group, Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three/examples/jsm/Addons.js";



export default function WallCorner(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<Group>(null);
  const { nodes, materials } = useGLTF("/wallCorner.gltf.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive
        material={materials.Stone}
        object={nodes.Cube4531}
        receiveShadow
        position={[0.0001, 0.0001, 0.0001]}
      />
      <primitive
        material={materials.StoneDark}
        object={nodes["Cube4531_1"]}
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("/wallCorner.gltf.glb");
