/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useMemo, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group } from "three";

export default function Wall(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<Group>(null);
  const { nodes, materials } = useGLTF("/wall.gltf.glb");
  const node0 = useMemo(() => nodes.Cube4530.clone(), [nodes]);
  const node1 = useMemo(() => nodes["Cube4530"].clone(), [nodes]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group userData={{ name: "wall" }}>
        <primitive
          material={materials.Stone}
          object={node0}
          receiveShadow
          position={[0.0001, 0.0001, 0.0001]}
        />
        <primitive
          material={materials.Stone}
          object={node1}
          receiveShadow
          position={[0.0001, 0.0001, 0.0001]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/wall.gltf.glb");
