/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group } from "three";

export default function Wall(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<Group>();
  const { nodes, materials, scene } = useGLTF("/wall.gltf.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group userData={{ name: "wall" }}>
        <primitive
          material={materials.Stone}
          object={nodes.Cube4530}
          receiveShadow
          position={[0.0001, 0.0001, 0.0001]}
        />
        <primitive
          material={materials.Stone}
          object={nodes["Cube4530_1"]}
          receiveShadow
          position={[0.0001, 0.0001, 0.0001]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/wall.gltf.glb");
